// Parity pins: the TS parsers must produce byte-identical output to the
// Python parsers (backend/app/providers/serpapi_google_flights.py) over
// the same recorded fixtures. The goldens are generated by
// scripts/dump_parser_goldens.py -- re-run it if either side changes.

import { describe, expect, it } from "vitest";
import { buildMultiCityOption, cheapestMultiCityStep, parseResponse, partitionIntoSlices } from "../serpapi";
import type { FareLeg, MultiCityLeg } from "../types";
import roundTripFixture from "./fixtures/round_trip_yyz_kix.json";
import oneWayFixture from "./fixtures/one_way_yyz_kix.json";
import step1Fixture from "./fixtures/multi_city_yyz_ist_bkk_step1.json";
import step2Fixture from "./fixtures/multi_city_yyz_ist_bkk_step2.json";
import roundTripGolden from "./goldens/round_trip_yyz_kix.parsed.json";
import oneWayGolden from "./goldens/one_way_yyz_kix.parsed.json";
import multiCityGolden from "./goldens/multi_city_yyz_ist_bkk.assembled.json";

const QUERY = { currency: "CAD", maxStops: null };

interface RawLegFixture {
  departure_airport?: { id?: string; time?: string };
  arrival_airport?: { id?: string; time?: string };
  airline?: string;
  flight_number?: string;
  duration?: number;
}

// Mirror of serpapi.ts's private parseLeg, reachable through the fixture
// items the public helpers hand back.
function legsOf(item: { flights?: RawLegFixture[] } | null): FareLeg[] {
  const asResponse = { best_flights: item ? [{ ...item, price: 1 }] : [] };
  const [option] = parseResponse(asResponse, QUERY);
  return option?.outbound_legs ?? [];
}

describe("SerpApi parser parity with Python", () => {
  it("round trip fixture parses identically", () => {
    expect(parseResponse(roundTripFixture, QUERY)).toEqual(roundTripGolden);
  });

  it("one-way fixture parses identically", () => {
    expect(parseResponse(oneWayFixture, QUERY)).toEqual(oneWayGolden);
  });

  it("multi-city chain assembles identically", () => {
    const legs: MultiCityLeg[] = [
      { origin: "YYZ", destination: "IST", date: "2026-09-10" },
      { origin: "IST", destination: "BKK", date: "2026-09-15" },
    ];

    const chosen1 = cheapestMultiCityStep(step1Fixture);
    expect(chosen1?.departure_token).toBe(multiCityGolden.step1_chosen_token);

    const chosen2 = cheapestMultiCityStep(step2Fixture);
    expect(chosen2).not.toBeNull();

    const collected = [...legsOf(chosen1), ...legsOf(chosen2)];
    const option = buildMultiCityOption(collected, chosen2!.price!, legs, { currency: "CAD", maxStops: null });
    expect(option).toEqual(multiCityGolden.option);
  });

  it("partitions a same-flight connection inside a slice, not as a city stop", () => {
    const mkLeg = (from: string, to: string, dep: string, arr: string): FareLeg => ({
      from_iata: from,
      to_iata: to,
      dep_time: dep,
      arr_time: arr,
      carrier: "AC",
      flight_number: "AC1",
      duration_min: 60,
    });
    // YYZ -> (FRA connection) -> IST, then IST -> BKK: 3 flat legs, 2
    // requested legs. The FRA hop must stay inside slice 1.
    const flat = [
      mkLeg("YYZ", "FRA", "2026-09-10T10:00", "2026-09-10T22:00"),
      mkLeg("FRA", "IST", "2026-09-11T01:00", "2026-09-11T04:00"),
      mkLeg("IST", "BKK", "2026-09-15T09:00", "2026-09-15T18:00"),
    ];
    const requested: MultiCityLeg[] = [
      { origin: "YYZ", destination: "IST", date: "2026-09-10" },
      { origin: "IST", destination: "BKK", date: "2026-09-15" },
    ];
    const slices = partitionIntoSlices(flat, requested);
    expect(slices).toHaveLength(2);
    expect(slices[0].legs).toHaveLength(2);
    expect(slices[0].stops).toBe(1);
    expect(slices[0].layovers).toEqual([["FRA", 180]]);
    expect(slices[1].legs).toHaveLength(1);
    expect(slices[1].stops).toBe(0);
  });
});
